// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Echat user's profile (id, username, name, bio).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const { data, error } = await sb(ctx).from("profiles").select("id, username, name, bio, avatar_url, is_online").eq("id", userId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { id: userId }) }],
      structuredContent: { profile: data ?? { id: userId } }
    };
  }
});

// src/lib/mcp/tools/list-recent-chats.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_chats_default = defineTool2({
  name: "list_recent_chats",
  title: "List recent chats",
  description: "List the signed-in user's most recent 1-to-1 Echat chats, ordered by last message time.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of chats to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("chats").select("id, participant_1, participant_2, last_message, last_message_time, last_sender_id").order("last_message_time", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { chats: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_messages_default = defineTool3({
  name: "list_messages",
  title: "List chat messages",
  description: "List the most recent messages in a 1-to-1 Echat chat by chat_id (RLS enforces access).",
  inputSchema: {
    chat_id: z2.string().uuid().describe("The Echat chat id (UUID)."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max messages (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ chat_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("messages").select("id, chat_id, sender_id, receiver_id, content, message_type, created_at, status").eq("chat_id", chat_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).slice().reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { messages: rows }
    };
  }
});

// src/lib/mcp/tools/search-users.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_users_default = defineTool4({
  name: "search_users",
  title: "Search Echat users",
  description: "Search Echat users by username or display name (case-insensitive). Returns public profile fields only.",
  inputSchema: {
    query: z3.string().trim().min(1).max(64).describe("Username or name fragment."),
    limit: z3.number().int().min(1).max(25).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const pattern = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await sb4(ctx).from("profiles").select("id, username, name, avatar_url, bio, is_online").or(`username.ilike.${pattern},name.ilike.${pattern}`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { users: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-note.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_note_default = defineTool5({
  name: "save_note",
  title: "Save a note to Saved Messages",
  description: "Save a personal text note to the user's Echat Saved Messages.",
  inputSchema: {
    note: z4.string().trim().min(1).max(4e3).describe("The note text to save.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("saved_messages").insert({ user_id: ctx.getUserId(), note }).select("id, note, saved_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved: ${data.id}` }],
      structuredContent: { saved: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ldocprioqcxxzadisoii";
var mcp_default = defineMcp({
  name: "echat-mcp",
  title: "Echat",
  version: "0.1.0",
  instructions: "Tools for the Echat super-app. Read the signed-in user's chats and messages, search Echat users, and save notes to Saved Messages. All actions run as the authenticated Echat user; RLS is enforced.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_recent_chats_default, list_messages_default, search_users_default, save_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
